#pragma once

#define INSTANCING 1
#define DEBUG_PIXEL 0
#define MULTI_THREADING 1
#define DAVID_ZOOM 0
#define INTERSECTION_STACK_SIZE 64
#define BACKFACE_CULLING 1
#define COMMAND_LINE_INPUT 0

#if DEBUG_PIXEL
#define WIDTH 430
#define HEIGHT 30
#endif
